// Auto-generated by VibeStack — SLOT markers replaced by LLM during code generation
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_authenticated/ingredients/$id')({
  component: IngredientsDetailPage,
})

function IngredientsDetailPage() {
  // {/* SLOT: DETAIL_PAGE — LLM fills component body for entity: ingredients */}
  return <div className="p-4">Loading ingredients detail...</div>
}
