// Auto-generated by VibeStack — SLOT markers replaced by LLM during code generation
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_authenticated/recipes')({
  component: RecipesListPage,
})

function RecipesListPage() {
  // {/* SLOT: LIST_PAGE — LLM fills component body for entity: recipes */}
  return <div className="p-4">Loading recipes...</div>
}
