// Auto-generated by VibeStack — SLOT markers replaced by LLM during code generation
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_authenticated/recipe-tags/$id')({
  component: RecipeTagsDetailPage,
})

function RecipeTagsDetailPage() {
  // {/* SLOT: DETAIL_PAGE — LLM fills component body for entity: recipe_tags */}
  return <div className="p-4">Loading recipe_tags detail...</div>
}
