// Auto-generated by VibeStack — SLOT markers replaced by LLM during code generation
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_authenticated/recipe-ingredients')({
  component: RecipeIngredientsListPage,
})

function RecipeIngredientsListPage() {
  // {/* SLOT: LIST_PAGE — LLM fills component body for entity: recipe_ingredients */}
  return <div className="p-4">Loading recipe-ingredients...</div>
}
