// Auto-generated by VibeStack — SLOT markers replaced by LLM during code generation
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_authenticated/recipes/$id')({
  component: RecipesDetailPage,
})

function RecipesDetailPage() {
  // {/* SLOT: DETAIL_PAGE — LLM fills component body for entity: recipes */}
  return <div className="p-4">Loading recipes detail...</div>
}
