// Auto-generated by VibeStack — SLOT markers replaced by LLM during code generation
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_authenticated/tags/$id')({
  component: TagsDetailPage,
})

function TagsDetailPage() {
  // {/* SLOT: DETAIL_PAGE — LLM fills component body for entity: tags */}
  return <div className="p-4">Loading tags detail...</div>
}
