// Auto-generated by VibeStack — SLOT markers replaced by LLM during code generation
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_authenticated/tags')({
  component: TagsListPage,
})

function TagsListPage() {
  // {/* SLOT: LIST_PAGE — LLM fills component body for entity: tags */}
  return <div className="p-4">Loading tags...</div>
}
